apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: front
data:
  test: hola
  nginx: |
    server {
        listen 8080;
        server_name localhost;

        location / {
            root    /usr/share/nginx/html;
            index   index.html index.htm;
        }

        error_page  500 502 503 504 /50x.html;
        location = /50x.html {
            root    /ur/share/nginx/html;
        }
    }
---
apiVersion: apps/v1 # apps = APIGROUP
kind: Deployment
metadata: # Deployment medatada
  name: deployment-test
  labels:
    app: front
spec: # ReplicaSet
  replicas: 1
  selector:
    matchLabels:
      app: front
  template: # Pod
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-vol
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-vol
          configMap:
            name: nginx-config
            items:
              - key: nginx
                path: default.conf
