apiVersion: v1
kind: Service
metadata: # Service metadata
  name: my-service1
  labels:
    app: backend
spec:
  type: NodePort # Type of service
  selector: # What label are we going to use to observe the pods
    app: front
  ports:
    - protocol: TCP
      port: 8080 # Where the service is going to hear
      targetPort: 80 # Which port the service is going to consume
---
apiVersion: apps/v1 # apps = APIGROUP
kind: Deployment
metadata: # Deployment medatada
  annotations:
    kubernetes.io/change-cause: "Changes port to 110" # CHANGE-CAUSE when updating deployment
  name: deployment-test1
  labels:
    app: backend
spec: # ReplicaSet
  revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template: # Pod
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
