apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
spec:
  containers:
    - name: cpu-demo-ctr
      image: vish/stress
      resources:
        limits:
          cpu: "1" # or cpu: "1000m" -> milli cores, is the same
        requests:
          cpu: "0.5"
      args:
        - -cpus
        - "2" # This value is above the limit so the pod should be reset, but not
          # K8s is not going to reset the pod. K8s is going to limit the CPU
          # to the limits value.
