# CLUSTERROLE ADMIN: In this case it is not necessary to create a Cluster Role because
# we are going to use the admin one: `kubectl get clusterroles`

# Cluster Role Binding. It has not namespace associated
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-custom-euclidean
subject:
  - kind: User
    name: euclidean
    apiGroup: rbac.authorization.k8s.io
roleRef: # Specifies the binding to a Role or a ClusterRole
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
