# GROUPROLE
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scv-clusterrole
rules:
  - apiGroups: [""] # Indicates the core API group
    resources: ["services"]
    verbs: ["*"] # RBAC all verbs chosen
---
# Cluster Role Binding. It has not namespace associated
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-svc
subject:
  - kind: Group
    name: dev # Group Name
    apiGroup: rbac.authorization.k8s.io
roleRef: # Specifies the binding to a Role or a ClusterRole
  kind: ClusterRole
  name: scv-clusterrole
  apiGroup: rbac.authorization.k8s.io
